### ISSUE TITLE
ansible module

### ISSUE THREAD

**Issue by Hashfyre** [razorpay/alohomora#3]
Write an `ansible-module` for `alohomora`.

Spec:
```
  - name: < task name>
    alohomora:
      command: <create | cast | store>
      template: <jinja2 template file source>
      region: <aws region>
      env: <string>
      app: <string>
```
